### ISSUE TITLE
I like the proyect but...

### ISSUE THREAD

**Issue by ediazrod** [0xDiSk/NVMe-SSD-HDD-S.M.A.R.T-Monitoring#11]
I like the project I love to share my disk info, but I like be able to use all the data from other and will be great be more transparent with all the data collected. 

Maybe some big data will be on order but nobody want to share their data with no exact information how to be used or by who.

Regards!

**Comment by 0xDiSk** [comment]
Hi :)

You can view any data you want, you just need the hash of the shared disk info which is viewable on main site.

Example:
https://diskcheck.monster/view/147774b2080cfbfe19b5cfe00bfdfe87e0e087014920f7bbf76d459cca408b77/_dev_sdg/1664
then you can go for lower ids like there:
https://diskcheck.monster/view/147774b2080cfbfe19b5cfe00bfdfe87e0e087014920f7bbf76d459cca408b77/_dev_sdg/1663 and so on...
