### ISSUE TITLE
"Accumulated power on time"

### ISSUE THREAD

**Issue by 0xDiSk** [0xDiSk/NVMe-SSD-HDD-S.M.A.R.T-Monitoring#5]
Need to update parsing of "Accumulated power on time"

Example:
https://diskcheck.co/view/0744014e68927b9597cbd8bdde3da15da3c4c51247b1b0296c323a3535d19b41/_dev_sda/1

**Comment by scriptzteam** [comment]
Fixed :)

**Comment by 0xDiSk** [comment]
Fixed :)
