### ISSUE TITLE
Partner with Scrutiny?

### ISSUE THREAD

**Issue by AnalogJ** [0xDiSk/NVMe-SSD-HDD-S.M.A.R.T-Monitoring#6]
Hey!
I'm the developer of [Scrutiny](https://github.com/AnalogJ/scrutiny) a self-hosted tool for analyzing SMART disk health and displaying it in a friendly UI. 
In addition to the webUI one of the most valuable features of Scrutiny is its ability to predict drive failure using BackBlaze's failure data. The issue is that their data is definitely Datacenter specific and I've had a task on my backlog for long time to allow my users to Opt-In to data collection so I can build my own (hopefully even larger) dataset of failure predictions. See https://github.com/AnalogJ/scrutiny/issues/10

Your project seems to have a different goal, but maybe you'd be would be willing to be another data source pushing SMART data to an open/shared data collection API?

**Comment by 0xDiSk** [comment]
Hi :)

You got it wrong.
When someone run smart.sh script, it send s.m.a.r.t. data to our api. 
We won´t re-send the data again to any other api.
