### ISSUE TITLE
Crontab issue "smartctl: not found" on Proxmox servers

### ISSUE THREAD

**Issue by kyob** [0xDiSk/NVMe-SSD-HDD-S.M.A.R.T-Monitoring#7]
1. I added script to crontab:

> Run cron once a day:
crontab -e
0 0 * * * wget -qO- https://diskcheck.co/smart.sh | sh && wget -qO- https://diskcheck.co/smart-test.sh | sh

2. and then I recieve error when it's execute:
```
sh: 10: smartctl: not found
sh: 2: smartctl: not found
```

3. but when I execute direct from CLI there is no errors:
` wget -qO- https://diskcheck.co/smart.sh | sh && wget -qO- https://diskcheck.co/smart-test.sh | sh`

4.  **smartctl** is installed
```bash
!root@pve1:~# which smartctl
/usr/sbin/smartctl
!root@pve1:~# smartctl -v
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.11.22-7-pve] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=======> ARGUMENT REQUIRED FOR OPTION: v
=======> VALID ARGUMENTS ARE:
	help
	N,raw8[:012345rvwz][,ATTR_NAME]
	N,raw16[:012345rvwz][,ATTR_NAME]
	N,raw48[:012345rvwz][,ATTR_NAME]
	N,hex48[:012345rvwz][,ATTR_NAME]
	N,raw56[:012345rvwz][,ATTR_NAME]
	N,hex56[:012345rvwz][,ATTR_NAME]
	N,raw64[:012345rvwz][,ATTR_NAME]
	N,hex64[:012345rvwz][,ATTR_NAME]
	N,raw16(raw16)[:012345rvwz][,ATTR_NAME]
	N,raw16(avg16)[:012345rvwz][,ATTR_NAME]
	N,raw24(raw8)[:012345rvwz][,ATTR_NAME]
	N,raw24/raw24[:012345rvwz][,ATTR_NAME]
	N,raw24/raw32[:012345rvwz][,ATTR_NAME]
	N,sec2hour[:012345rvwz][,ATTR_NAME]
	N,min2hour[:012345rvwz][,ATTR_NAME]
	N,halfmin2hour[:012345rvwz][,ATTR_NAME]
	N,msec24hour32[:012345rvwz][,ATTR_NAME]
	N,tempminmax[:012345rvwz][,ATTR_NAME]
	N,temp10x[:012345rvwz][,ATTR_NAME]
	9,halfminutes
	9,minutes
	9,seconds
	9,temp
	192,emergencyretractcyclect
	193,loadunload
	194,10xCelsius
	194,unknown
	197,increasing
	198,offlinescanuncsectorct
	198,increasing
	200,writeerrorcount
	201,detectedtacount
	220,temp
<=======

Use smartctl -h to get a usage summary

```
5. Problem occurs only on my **Proxmox 7.2-7** servers

- Linux Distribution:		Debian GNU/Linux 11 (bullseye)
- Linux Kernel:			5.11.22-7-pve

**Comment by 0xDiSk** [comment]
Hi :)

Seems like its fault of cron have no rights to run smartctl? idk why it wont find it when its installed - thats not a fault of script, that has something to-do with system maybe.

Try create new script example.sh:
nano example.sh
add this -> smartctl -v
and save it -> ctrl + x
run it as -> sh example.sh
does it output?

its probably how you run it, its root? or other user?
also you can just save the scripts and run them locally

wget https://diskcheck.co/smart.sh
then rus as -> sh smart.sh

if its cron that causing a problems run it in loop (screen or tmux):
```
while true;do sh smart.sh;sleep 3600;done
```
or
```
while true;do wget -qO- https://diskcheck.co/smart.sh | sh && wget -qO- https://diskcheck.co/smart-test.sh | sh;sleep 3600;done
```

**Comment by kyob** [comment]
OK you are right it's not script problem :)

**Comment by kyob** [comment]
### SOLUTION
I removed job from **crontab** and put is script in directory **cron.daily**
